version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    allow:
      # include indirect dependencies
      - dependency-type: all
    groups:
      tracing:
        patterns:
          - opentelemetry*
          - tracing*
      async_graphql:
        # Split async graphql into its own group as it doesn't follow semver
        patterns:
          - async-graphql*
      patch:
        update-types:
          - patch
