apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "numtracker.fullname" . }}
  labels:
    {{- include "numtracker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: numtracker
  template:
    metadata:
      labels:
        app: numtracker
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: graphql
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: numtracker-data
              mountPath: /data
          env:
            - name: NUMTRACKER_DB
              value: {{ .Values.numtracker.dbLocation }}
            - name: NUMTRACKER_PORT
              value: "{{ .Values.numtracker.port -}}"
            {{ if .Values.numtracker.tracing.enabled }}
            - name: NUMTRACKER_TRACING
              value: {{ .Values.numtracker.tracing.host }}
            - name: NUMTRACKER_TRACING_LEVEL
              value: {{ .Values.numtracker.tracing.level }}
            {{- end }}
            {{ if .Values.numtracker.auth.enabled -}}
            - name: NUMTRACKER_AUTH_HOST
              value: {{ .Values.numtracker.auth.host }}
            - name: NUMTRACKER_AUTH_ACCESS
              value: {{ .Values.numtracker.auth.access }}
            - name: NUMTRACKER_AUTH_ADMIN
              value: {{ .Values.numtracker.auth.admin }}
            {{- end }}
      volumes:
        - name: numtracker-data
          persistentVolumeClaim:
            claimName: {{ .Values.numtracker.storage.pvcName }}
