kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.numtracker.storage.claimName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.numtracker.storage.size }}
