kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.numtracker.storage.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.numtracker.storage.size }}
