apiVersion: v2
name: numtracker
home: https://github.com/DiamondLightSource/numtracker
description: Helm chart to deploy the numtracker service for unifying instrument filenaming
type: application

# These versions are ignored and are automatically set via the CI process to the version from the tag

# This is the version of the helm chart
version: 0.0.0
# This is the version number of the application being deployed by the helm chart
appVersion: "0.0.0"
